// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getHistory, getModels, type Options, root, switchModel } from '../sdk.gen';
import type { GetHistoryData, GetHistoryResponse, GetModelsData, GetModelsResponse, RootData, SwitchModelData, SwitchModelError } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const rootQueryKey = (options?: Options<RootData>) => createQueryKey('root', options);

/**
 * Root
 */
export const rootOptions = (options?: Options<RootData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof rootQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await root({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: rootQueryKey(options)
});

export const getModelsQueryKey = (options?: Options<GetModelsData>) => createQueryKey('getModels', options);

/**
 * Get Models
 *
 * List available speech-to-text models.
 */
export const getModelsOptions = (options?: Options<GetModelsData>) => queryOptions<GetModelsResponse, DefaultError, GetModelsResponse, ReturnType<typeof getModelsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getModels({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getModelsQueryKey(options)
});

export const getHistoryQueryKey = (options?: Options<GetHistoryData>) => createQueryKey('getHistory', options);

/**
 * Get History
 *
 * Get transcription history.
 */
export const getHistoryOptions = (options?: Options<GetHistoryData>) => queryOptions<GetHistoryResponse, DefaultError, GetHistoryResponse, ReturnType<typeof getHistoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHistory({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHistoryQueryKey(options)
});

/**
 * Switch Model
 *
 * Manually switch model via REST (optional, mostly for testing).
 */
export const switchModelMutation = (options?: Partial<Options<SwitchModelData>>): UseMutationOptions<unknown, SwitchModelError, Options<SwitchModelData>> => {
    const mutationOptions: UseMutationOptions<unknown, SwitchModelError, Options<SwitchModelData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await switchModel({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
