// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetHistoryData, GetHistoryResponses, GetModelsData, GetModelsResponses, GetModelStatusData, GetModelStatusResponses, RootData, RootResponses, SwitchModelData, SwitchModelErrors, SwitchModelResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Root
 */
export const root = <ThrowOnError extends boolean = false>(options?: Options<RootData, ThrowOnError>) => (options?.client ?? client).get<RootResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Get Models
 *
 * List available speech-to-text models.
 */
export const getModels = <ThrowOnError extends boolean = false>(options?: Options<GetModelsData, ThrowOnError>) => (options?.client ?? client).get<GetModelsResponses, unknown, ThrowOnError>({ url: '/api/v1/models', ...options });

/**
 * Get History
 *
 * Get transcription history.
 */
export const getHistory = <ThrowOnError extends boolean = false>(options?: Options<GetHistoryData, ThrowOnError>) => (options?.client ?? client).get<GetHistoryResponses, unknown, ThrowOnError>({ url: '/api/v1/history', ...options });

/**
 * Switch Model
 *
 * Manually switch model via REST (optional, mostly for testing).
 */
export const switchModel = <ThrowOnError extends boolean = false>(options: Options<SwitchModelData, ThrowOnError>) => (options.client ?? client).post<SwitchModelResponses, SwitchModelErrors, ThrowOnError>({ url: '/models/switch', ...options });

/**
 * Get Model Status
 *
 * Get the status of the currently loaded model.
 */
export const getModelStatus = <ThrowOnError extends boolean = false>(options?: Options<GetModelStatusData, ThrowOnError>) => (options?.client ?? client).get<GetModelStatusResponses, unknown, ThrowOnError>({ url: '/api/v1/models/status', ...options });
