// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:8000' | (string & {})
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * ModelInfo
 *
 * Information about an available STT model.
 */
export type ModelInfo = {
  /**
   * Id
   */
  id: string
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description: string
  /**
   * Workflow Type
   */
  workflow_type?: 'streaming' | 'buffered'
  /**
   * Expected Latency Ms
   */
  expected_latency_ms?: [number, number]
}

/**
 * ModelStatus
 *
 * Current status of the model system.
 */
export type ModelStatus = {
  /**
   * Current Model
   */
  current_model?: string | null
  /**
   * Is Loaded
   */
  is_loaded: boolean
  /**
   * Status
   */
  status: string
}

/**
 * SwitchModelResponse
 *
 * Response for model switch operation.
 */
export type SwitchModelResponse = {
  /**
   * Status
   */
  status: string
  /**
   * Current Model
   */
  current_model: string
}

/**
 * TranscriptionLog
 *
 * Database model for storing transcription history.
 *
 * Each record represents a transcription session (one recording session).
 */
export type TranscriptionLog = {
  /**
   * Id
   */
  id?: number | null
  /**
   * Session Id
   *
   * Unique session identifier
   */
  session_id: string
  /**
   * Model Id
   *
   * Model used for transcription
   */
  model_id: string
  /**
   * Content
   *
   * Transcribed text content
   */
  content: string
  /**
   * Latency Ms
   *
   * Processing latency in milliseconds
   */
  latency_ms?: number
  /**
   * Created At
   *
   * Timestamp of creation
   */
  created_at?: string
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
}

export type RootData = {
  body?: never
  path?: never
  query?: never
  url: '/'
}

export type RootResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type HealthCheckData = {
  body?: never
  path?: never
  query?: never
  url: '/health'
}

export type HealthCheckResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetModelsData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/models'
}

export type GetModelsResponses = {
  /**
   * Response Get Models Api V1 Models Get
   *
   * Successful Response
   */
  200: Array<ModelInfo>
}

export type GetModelsResponse = GetModelsResponses[keyof GetModelsResponses]

export type GetHistoryData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     */
    page?: number
    /**
     * Limit
     */
    limit?: number
    /**
     * Search
     */
    search?: string
    /**
     * Model
     */
    model?: string
    /**
     * Min Latency
     */
    min_latency?: number
    /**
     * Max Latency
     */
    max_latency?: number
    /**
     * Start Date
     */
    start_date?: string
    /**
     * End Date
     */
    end_date?: string
  }
  url: '/api/v1/history'
}

export type GetHistoryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetHistoryError = GetHistoryErrors[keyof GetHistoryErrors]

export type GetHistoryResponses = {
  /**
   * Response Get History Api V1 History Get
   *
   * Successful Response
   */
  200: Array<TranscriptionLog>
}

export type GetHistoryResponse = GetHistoryResponses[keyof GetHistoryResponses]

export type SwitchModelData = {
  body?: never
  path?: never
  query: {
    /**
     * Model
     */
    model: string
  }
  url: '/api/v1/models/switch'
}

export type SwitchModelErrors = {
  /**
   * Invalid model name
   */
  400: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
  /**
   * Model failed to start
   */
  503: unknown
}

export type SwitchModelError = SwitchModelErrors[keyof SwitchModelErrors]

export type SwitchModelResponses = {
  /**
   * Successful Response
   */
  200: SwitchModelResponse
}

export type SwitchModelResponse2 =
  SwitchModelResponses[keyof SwitchModelResponses]

export type GetModelStatusData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/models/status'
}

export type GetModelStatusResponses = {
  /**
   * Successful Response
   */
  200: ModelStatus
}

export type GetModelStatusResponse =
  GetModelStatusResponses[keyof GetModelStatusResponses]
