// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ModelInfo
 */
export type ModelInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * TranscriptionLog
 */
export type TranscriptionLog = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Content
     */
    content: string;
    /**
     * Latency Ms
     */
    latency_ms: number;
    /**
     * Created At
     */
    created_at?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/models';
};

export type GetModelsResponses = {
    /**
     * Response Get Models Api V1 Models Get
     *
     * Successful Response
     */
    200: Array<ModelInfo>;
};

export type GetModelsResponse = GetModelsResponses[keyof GetModelsResponses];

export type GetHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/history';
};

export type GetHistoryResponses = {
    /**
     * Response Get History Api V1 History Get
     *
     * Successful Response
     */
    200: Array<TranscriptionLog>;
};

export type GetHistoryResponse = GetHistoryResponses[keyof GetHistoryResponses];

export type SwitchModelData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Model
         */
        model: string;
    };
    url: '/models/switch';
};

export type SwitchModelErrors = {
    /**
     * Invalid model name
     */
    400: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Model failed to start
     */
    503: unknown;
};

export type SwitchModelError = SwitchModelErrors[keyof SwitchModelErrors];

export type SwitchModelResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
