// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * ModelInfo
 */
export const zModelInfo = z.object({
    id: z.string(),
    name: z.string(),
    description: z.string()
});

/**
 * TranscriptionLog
 */
export const zTranscriptionLog = z.object({
    id: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    session_id: z.string(),
    model_id: z.string(),
    content: z.string(),
    latency_ms: z.number(),
    created_at: z.optional(z.iso.datetime())
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError))
});

export const zRootData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetModelsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Response Get Models Api V1 Models Get
 *
 * Successful Response
 */
export const zGetModelsResponse = z.array(zModelInfo);

export const zGetHistoryData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Response Get History Api V1 History Get
 *
 * Successful Response
 */
export const zGetHistoryResponse = z.array(zTranscriptionLog);

export const zSwitchModelData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        model: z.string()
    })
});

export const zGetModelStatusData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});
